development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.db

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.db

production:
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  database: xxx_production
  host: localhost
  pool: 5
  username: xxx_app
  password: postgres
